### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_pixtx_config_query_type_t
  commentId: T:IGCLWrapper.ctl_pixtx_config_query_type_t
  id: ctl_pixtx_config_query_type_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  - IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  - IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  langs:
  - csharp
  - vb
  name: ctl_pixtx_config_query_type_t
  nameWithType: ctl_pixtx_config_query_type_t
  fullName: IGCLWrapper.ctl_pixtx_config_query_type_t
  type: Enum
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_pixtx_config_query_type_t
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public enum ctl_pixtx_config_query_type_t
    content.vb: Public Enum ctl_pixtx_config_query_type_t
- uid: IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  commentId: F:IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  id: CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  parent: IGCLWrapper.ctl_pixtx_config_query_type_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  nameWithType: ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  fullName: IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
    startLine: 6
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_CONFIG_QUERY_TYPE_CAPABILITY = 0
    return:
      type: IGCLWrapper.ctl_pixtx_config_query_type_t
- uid: IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  commentId: F:IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  id: CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  parent: IGCLWrapper.ctl_pixtx_config_query_type_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  nameWithType: ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  fullName: IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
    startLine: 9
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_CONFIG_QUERY_TYPE_CURRENT = 1
    return:
      type: IGCLWrapper.ctl_pixtx_config_query_type_t
- uid: IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  commentId: F:IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  id: CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  parent: IGCLWrapper.ctl_pixtx_config_query_type_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  nameWithType: ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  fullName: IGCLWrapper.ctl_pixtx_config_query_type_t.CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_CONFIG_QUERY_TYPE_MAX
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_query_type_t.cs
    startLine: 12
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_CONFIG_QUERY_TYPE_MAX = 2
    return:
      type: IGCLWrapper.ctl_pixtx_config_query_type_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: IGCLWrapper.ctl_pixtx_config_query_type_t
  commentId: T:IGCLWrapper.ctl_pixtx_config_query_type_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_pixtx_config_query_type_t.html
  name: ctl_pixtx_config_query_type_t
  nameWithType: ctl_pixtx_config_query_type_t
  fullName: IGCLWrapper.ctl_pixtx_config_query_type_t
