### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_firmware_config_flag_t
  commentId: T:IGCLWrapper.ctl_firmware_config_flag_t
  id: ctl_firmware_config_flag_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  - IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  - IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_MAX
  langs:
  - csharp
  - vb
  name: ctl_firmware_config_flag_t
  nameWithType: ctl_firmware_config_flag_t
  fullName: IGCLWrapper.ctl_firmware_config_flag_t
  type: Enum
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_firmware_config_flag_t
    path: ../IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public enum ctl_firmware_config_flag_t
    content.vb: Public Enum ctl_firmware_config_flag_t
- uid: IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  commentId: F:IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  id: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  parent: IGCLWrapper.ctl_firmware_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  nameWithType: ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  fullName: IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE
    path: ../IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
    startLine: 6
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_CAPABLE = 1
    return:
      type: IGCLWrapper.ctl_firmware_config_flag_t
- uid: IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  commentId: F:IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  id: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  parent: IGCLWrapper.ctl_firmware_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  nameWithType: ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  fullName: IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE
    path: ../IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
    startLine: 9
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_FIRMWARE_CONFIG_FLAG_IS_DEVICE_LINK_SPEED_DOWNGRADE_ACTIVE = 2
    return:
      type: IGCLWrapper.ctl_firmware_config_flag_t
- uid: IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_MAX
  commentId: F:IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_MAX
  id: CTL_FIRMWARE_CONFIG_FLAG_MAX
  parent: IGCLWrapper.ctl_firmware_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_FIRMWARE_CONFIG_FLAG_MAX
  nameWithType: ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_MAX
  fullName: IGCLWrapper.ctl_firmware_config_flag_t.CTL_FIRMWARE_CONFIG_FLAG_MAX
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_FIRMWARE_CONFIG_FLAG_MAX
    path: ../IGCLWrapper/cs_generated/ctl_firmware_config_flag_t.cs
    startLine: 12
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_FIRMWARE_CONFIG_FLAG_MAX = -2147483648
    return:
      type: IGCLWrapper.ctl_firmware_config_flag_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: IGCLWrapper.ctl_firmware_config_flag_t
  commentId: T:IGCLWrapper.ctl_firmware_config_flag_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_firmware_config_flag_t.html
  name: ctl_firmware_config_flag_t
  nameWithType: ctl_firmware_config_flag_t
  fullName: IGCLWrapper.ctl_firmware_config_flag_t
