### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_encoder_config_flag_t
  commentId: T:IGCLWrapper.ctl_encoder_config_flag_t
  id: ctl_encoder_config_flag_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MAX
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  - IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  langs:
  - csharp
  - vb
  name: ctl_encoder_config_flag_t
  nameWithType: ctl_encoder_config_flag_t
  fullName: IGCLWrapper.ctl_encoder_config_flag_t
  type: Enum
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_encoder_config_flag_t
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public enum ctl_encoder_config_flag_t
    content.vb: Public Enum ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 6
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY = 1
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 9
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY = 2
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  id: CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 12
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE = 4
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  id: CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 15
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE = 8
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  id: CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 18
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED = 16
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 21
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY = 32
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 24
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY = 64
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 27
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY = 128
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 30
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY = 256
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 33
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY = 512
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  id: CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 36
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY = 1024
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
- uid: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MAX
  commentId: F:IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MAX
  id: CTL_ENCODER_CONFIG_FLAG_MAX
  parent: IGCLWrapper.ctl_encoder_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_ENCODER_CONFIG_FLAG_MAX
  nameWithType: ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MAX
  fullName: IGCLWrapper.ctl_encoder_config_flag_t.CTL_ENCODER_CONFIG_FLAG_MAX
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_ENCODER_CONFIG_FLAG_MAX
    path: ../IGCLWrapper/cs_generated/ctl_encoder_config_flag_t.cs
    startLine: 39
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_ENCODER_CONFIG_FLAG_MAX = -2147483648
    return:
      type: IGCLWrapper.ctl_encoder_config_flag_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: IGCLWrapper.ctl_encoder_config_flag_t
  commentId: T:IGCLWrapper.ctl_encoder_config_flag_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_encoder_config_flag_t.html
  name: ctl_encoder_config_flag_t
  nameWithType: ctl_encoder_config_flag_t
  fullName: IGCLWrapper.ctl_encoder_config_flag_t
