### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_display_config_flag_t
  commentId: T:IGCLWrapper.ctl_display_config_flag_t
  id: ctl_display_config_flag_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  - IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  - IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  - IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  - IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_MAX
  langs:
  - csharp
  - vb
  name: ctl_display_config_flag_t
  nameWithType: ctl_display_config_flag_t
  fullName: IGCLWrapper.ctl_display_config_flag_t
  type: Enum
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_display_config_flag_t
    path: ../IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public enum ctl_display_config_flag_t
    content.vb: Public Enum ctl_display_config_flag_t
- uid: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  commentId: F:IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  id: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  parent: IGCLWrapper.ctl_display_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  nameWithType: ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  fullName: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE
    path: ../IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
    startLine: 6
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE = 1
    return:
      type: IGCLWrapper.ctl_display_config_flag_t
- uid: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  commentId: F:IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  id: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  parent: IGCLWrapper.ctl_display_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  nameWithType: ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  fullName: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED
    path: ../IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
    startLine: 9
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED = 2
    return:
      type: IGCLWrapper.ctl_display_config_flag_t
- uid: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  commentId: F:IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  id: CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  parent: IGCLWrapper.ctl_display_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  nameWithType: ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  fullName: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER
    path: ../IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
    startLine: 12
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER = 4
    return:
      type: IGCLWrapper.ctl_display_config_flag_t
- uid: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  commentId: F:IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  id: CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  parent: IGCLWrapper.ctl_display_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  nameWithType: ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  fullName: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED
    path: ../IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
    startLine: 15
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED = 8
    return:
      type: IGCLWrapper.ctl_display_config_flag_t
- uid: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_MAX
  commentId: F:IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_MAX
  id: CTL_DISPLAY_CONFIG_FLAG_MAX
  parent: IGCLWrapper.ctl_display_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_DISPLAY_CONFIG_FLAG_MAX
  nameWithType: ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_MAX
  fullName: IGCLWrapper.ctl_display_config_flag_t.CTL_DISPLAY_CONFIG_FLAG_MAX
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_DISPLAY_CONFIG_FLAG_MAX
    path: ../IGCLWrapper/cs_generated/ctl_display_config_flag_t.cs
    startLine: 18
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_DISPLAY_CONFIG_FLAG_MAX = -2147483648
    return:
      type: IGCLWrapper.ctl_display_config_flag_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: IGCLWrapper.ctl_display_config_flag_t
  commentId: T:IGCLWrapper.ctl_display_config_flag_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_display_config_flag_t.html
  name: ctl_display_config_flag_t
  nameWithType: ctl_display_config_flag_t
  fullName: IGCLWrapper.ctl_display_config_flag_t
