### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  commentId: T:IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  id: ctl_pixtx_config_opertaion_type_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  - IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  - IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  langs:
  - csharp
  - vb
  name: ctl_pixtx_config_opertaion_type_t
  nameWithType: ctl_pixtx_config_opertaion_type_t
  fullName: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  type: Enum
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_pixtx_config_opertaion_type_t
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public enum ctl_pixtx_config_opertaion_type_t
    content.vb: Public Enum ctl_pixtx_config_opertaion_type_t
- uid: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  commentId: F:IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  id: CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  parent: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  nameWithType: ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  fullName: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
    startLine: 6
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_CONFIG_OPERTAION_TYPE_RESTORE_DEFAULT = 1
    return:
      type: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
- uid: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  commentId: F:IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  id: CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  parent: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  nameWithType: ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  fullName: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
    startLine: 9
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_CONFIG_OPERTAION_TYPE_SET_CUSTOM = 2
    return:
      type: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
- uid: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  commentId: F:IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  id: CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  parent: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  nameWithType: ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  fullName: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_config_opertaion_type_t.cs
    startLine: 12
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_CONFIG_OPERTAION_TYPE_MAX = 3
    return:
      type: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  commentId: T:IGCLWrapper.ctl_pixtx_config_opertaion_type_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_pixtx_config_opertaion_type_t.html
  name: ctl_pixtx_config_opertaion_type_t
  nameWithType: ctl_pixtx_config_opertaion_type_t
  fullName: IGCLWrapper.ctl_pixtx_config_opertaion_type_t
