### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_lace_aggr_config_t
  commentId: T:IGCLWrapper.ctl_lace_aggr_config_t
  id: ctl_lace_aggr_config_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_lace_aggr_config_t.AggrLevelMap
  - IGCLWrapper.ctl_lace_aggr_config_t.FixedAggressivenessLevelPercent
  langs:
  - csharp
  - vb
  name: ctl_lace_aggr_config_t
  nameWithType: ctl_lace_aggr_config_t
  fullName: IGCLWrapper.ctl_lace_aggr_config_t
  type: Struct
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_lace_aggr_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_lace_aggr_config_t
    path: ../IGCLWrapper/cs_generated/ctl_lace_aggr_config_t.cs
    startLine: 5
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public struct ctl_lace_aggr_config_t
    content.vb: Public Structure ctl_lace_aggr_config_t
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: IGCLWrapper.ctl_lace_aggr_config_t.FixedAggressivenessLevelPercent
  commentId: F:IGCLWrapper.ctl_lace_aggr_config_t.FixedAggressivenessLevelPercent
  id: FixedAggressivenessLevelPercent
  parent: IGCLWrapper.ctl_lace_aggr_config_t
  langs:
  - csharp
  - vb
  name: FixedAggressivenessLevelPercent
  nameWithType: ctl_lace_aggr_config_t.FixedAggressivenessLevelPercent
  fullName: IGCLWrapper.ctl_lace_aggr_config_t.FixedAggressivenessLevelPercent
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_lace_aggr_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: FixedAggressivenessLevelPercent
    path: ../IGCLWrapper/cs_generated/ctl_lace_aggr_config_t.cs
    startLine: 11
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public byte FixedAggressivenessLevelPercent
    return:
      type: System.Byte
    content.vb: Public FixedAggressivenessLevelPercent As Byte
- uid: IGCLWrapper.ctl_lace_aggr_config_t.AggrLevelMap
  commentId: F:IGCLWrapper.ctl_lace_aggr_config_t.AggrLevelMap
  id: AggrLevelMap
  parent: IGCLWrapper.ctl_lace_aggr_config_t
  langs:
  - csharp
  - vb
  name: AggrLevelMap
  nameWithType: ctl_lace_aggr_config_t.AggrLevelMap
  fullName: IGCLWrapper.ctl_lace_aggr_config_t.AggrLevelMap
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_lace_aggr_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: AggrLevelMap
    path: ../IGCLWrapper/cs_generated/ctl_lace_aggr_config_t.cs
    startLine: 15
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public ctl_lace_lux_aggr_map_t AggrLevelMap
    return:
      type: IGCLWrapper.ctl_lace_lux_aggr_map_t
    content.vb: Public AggrLevelMap As ctl_lace_lux_aggr_map_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: IGCLWrapper.ctl_lace_lux_aggr_map_t
  commentId: T:IGCLWrapper.ctl_lace_lux_aggr_map_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_lace_lux_aggr_map_t.html
  name: ctl_lace_lux_aggr_map_t
  nameWithType: ctl_lace_lux_aggr_map_t
  fullName: IGCLWrapper.ctl_lace_lux_aggr_map_t
