### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t
  commentId: T:IGCLWrapper.ctl_pixtx_1dlut_config_t
  id: ctl_pixtx_1dlut_config_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.NumChannels
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.NumSamplesPerChannel
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.SamplingType
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.Size
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.Version
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.pSamplePositions
  - IGCLWrapper.ctl_pixtx_1dlut_config_t.pSampleValues
  langs:
  - csharp
  - vb
  name: ctl_pixtx_1dlut_config_t
  nameWithType: ctl_pixtx_1dlut_config_t
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t
  type: Struct
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_pixtx_1dlut_config_t
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public struct ctl_pixtx_1dlut_config_t
    content.vb: Public Structure ctl_pixtx_1dlut_config_t
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.Size
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.Size
  id: Size
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: Size
  nameWithType: ctl_pixtx_1dlut_config_t.Size
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.Size
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Size
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 7
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public uint Size
    return:
      type: System.UInt32
    content.vb: Public Size As UInteger
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.Version
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.Version
  id: Version
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: ctl_pixtx_1dlut_config_t.Version
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.Version
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Version
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 11
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public byte Version
    return:
      type: System.Byte
    content.vb: Public Version As Byte
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.SamplingType
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.SamplingType
  id: SamplingType
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: SamplingType
  nameWithType: ctl_pixtx_1dlut_config_t.SamplingType
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.SamplingType
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: SamplingType
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 14
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public ctl_pixtx_lut_sampling_type_t SamplingType
    return:
      type: IGCLWrapper.ctl_pixtx_lut_sampling_type_t
    content.vb: Public SamplingType As ctl_pixtx_lut_sampling_type_t
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.NumSamplesPerChannel
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.NumSamplesPerChannel
  id: NumSamplesPerChannel
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: NumSamplesPerChannel
  nameWithType: ctl_pixtx_1dlut_config_t.NumSamplesPerChannel
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.NumSamplesPerChannel
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: NumSamplesPerChannel
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 18
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public uint NumSamplesPerChannel
    return:
      type: System.UInt32
    content.vb: Public NumSamplesPerChannel As UInteger
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.NumChannels
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.NumChannels
  id: NumChannels
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: NumChannels
  nameWithType: ctl_pixtx_1dlut_config_t.NumChannels
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.NumChannels
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: NumChannels
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 22
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public uint NumChannels
    return:
      type: System.UInt32
    content.vb: Public NumChannels As UInteger
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.pSampleValues
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.pSampleValues
  id: pSampleValues
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: pSampleValues
  nameWithType: ctl_pixtx_1dlut_config_t.pSampleValues
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.pSampleValues
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: pSampleValues
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 25
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public double* pSampleValues
    return:
      type: System.Double*
    content.vb: Public pSampleValues As Double*
- uid: IGCLWrapper.ctl_pixtx_1dlut_config_t.pSamplePositions
  commentId: F:IGCLWrapper.ctl_pixtx_1dlut_config_t.pSamplePositions
  id: pSamplePositions
  parent: IGCLWrapper.ctl_pixtx_1dlut_config_t
  langs:
  - csharp
  - vb
  name: pSamplePositions
  nameWithType: ctl_pixtx_1dlut_config_t.pSamplePositions
  fullName: IGCLWrapper.ctl_pixtx_1dlut_config_t.pSamplePositions
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: pSamplePositions
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_1dlut_config_t.cs
    startLine: 28
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public double* pSamplePositions
    return:
      type: System.Double*
    content.vb: Public pSamplePositions As Double*
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: IGCLWrapper.ctl_pixtx_lut_sampling_type_t
  commentId: T:IGCLWrapper.ctl_pixtx_lut_sampling_type_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_pixtx_lut_sampling_type_t.html
  name: ctl_pixtx_lut_sampling_type_t
  nameWithType: ctl_pixtx_lut_sampling_type_t
  fullName: IGCLWrapper.ctl_pixtx_lut_sampling_type_t
- uid: System.Double*
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double*
  nameWithType: double*
  fullName: double*
  nameWithType.vb: Double*
  fullName.vb: Double*
  name.vb: Double*
  spec.csharp:
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '*'
  spec.vb:
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '*'
