### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  commentId: T:IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  id: ctl_pixtx_pipe_set_config_flag_t
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  - IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  langs:
  - csharp
  - vb
  name: ctl_pixtx_pipe_set_config_flag_t
  nameWithType: ctl_pixtx_pipe_set_config_flag_t
  fullName: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  type: Enum
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_pipe_set_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ctl_pixtx_pipe_set_config_flag_t
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_pipe_set_config_flag_t.cs
    startLine: 3
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: public enum ctl_pixtx_pipe_set_config_flag_t
    content.vb: Public Enum ctl_pixtx_pipe_set_config_flag_t
- uid: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  commentId: F:IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  id: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  parent: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  nameWithType: ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  fullName: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_pipe_set_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_pipe_set_config_flag_t.cs
    startLine: 6
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_PERSIST_ACROSS_POWER_EVENTS = 1
    return:
      type: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
- uid: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  commentId: F:IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  id: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  parent: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  langs:
  - csharp
  - vb
  name: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  nameWithType: ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  fullName: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
  type: Field
  source:
    remote:
      path: IGCLWrapper/cs_generated/ctl_pixtx_pipe_set_config_flag_t.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX
    path: ../IGCLWrapper/cs_generated/ctl_pixtx_pipe_set_config_flag_t.cs
    startLine: 9
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  example: []
  syntax:
    content: CTL_PIXTX_PIPE_SET_CONFIG_FLAG_MAX = -2147483648
    return:
      type: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  commentId: T:IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t.html
  name: ctl_pixtx_pipe_set_config_flag_t
  nameWithType: ctl_pixtx_pipe_set_config_flag_t
  fullName: IGCLWrapper.ctl_pixtx_pipe_set_config_flag_t
