### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  commentId: T:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  id: EValues_BATTERY_BOOST_APP_FPS
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_DEFAULT
  - NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MAX
  - NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MIN
  - NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  - NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NUM_VALUES
  langs:
  - csharp
  - vb
  name: EValues_BATTERY_BOOST_APP_FPS
  nameWithType: EValues_BATTERY_BOOST_APP_FPS
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_BATTERY_BOOST_APP_FPS
    path: ../NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_BATTERY_BOOST_APP_FPS
    content.vb: Public Enum EValues_BATTERY_BOOST_APP_FPS
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MIN
  commentId: F:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MIN
  id: BATTERY_BOOST_APP_FPS_MIN
  parent: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  langs:
  - csharp
  - vb
  name: BATTERY_BOOST_APP_FPS_MIN
  nameWithType: EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MIN
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MIN
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: BATTERY_BOOST_APP_FPS_MIN
    path: ../NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: BATTERY_BOOST_APP_FPS_MIN = 1
    return:
      type: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MAX
  commentId: F:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MAX
  id: BATTERY_BOOST_APP_FPS_MAX
  parent: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  langs:
  - csharp
  - vb
  name: BATTERY_BOOST_APP_FPS_MAX
  nameWithType: EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MAX
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_MAX
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: BATTERY_BOOST_APP_FPS_MAX
    path: ../NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: BATTERY_BOOST_APP_FPS_MAX = 1023
    return:
      type: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  commentId: F:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  id: BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  parent: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  langs:
  - csharp
  - vb
  name: BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  nameWithType: EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NO_OVERRIDE
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: BATTERY_BOOST_APP_FPS_NO_OVERRIDE
    path: ../NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: BATTERY_BOOST_APP_FPS_NO_OVERRIDE = 0
    return:
      type: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NUM_VALUES
  id: BATTERY_BOOST_APP_FPS_NUM_VALUES
  parent: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  langs:
  - csharp
  - vb
  name: BATTERY_BOOST_APP_FPS_NUM_VALUES
  nameWithType: EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NUM_VALUES
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: BATTERY_BOOST_APP_FPS_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: BATTERY_BOOST_APP_FPS_NUM_VALUES = 3
    return:
      type: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_DEFAULT
  commentId: F:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_DEFAULT
  id: BATTERY_BOOST_APP_FPS_DEFAULT
  parent: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  langs:
  - csharp
  - vb
  name: BATTERY_BOOST_APP_FPS_DEFAULT
  nameWithType: EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_DEFAULT
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.BATTERY_BOOST_APP_FPS_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: BATTERY_BOOST_APP_FPS_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_BATTERY_BOOST_APP_FPS.cs
    startLine: 18
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: BATTERY_BOOST_APP_FPS_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  commentId: T:NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS.html
  name: EValues_BATTERY_BOOST_APP_FPS
  nameWithType: EValues_BATTERY_BOOST_APP_FPS
  fullName: NVAPIWrapper.EValues_BATTERY_BOOST_APP_FPS
