### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  commentId: T:NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  id: EValues_PS_OFFLINE_SHADER_COMPILER
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_DEFAULT
  - NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  - NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_OFF
  - NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_ON
  langs:
  - csharp
  - vb
  name: EValues_PS_OFFLINE_SHADER_COMPILER
  nameWithType: EValues_PS_OFFLINE_SHADER_COMPILER
  fullName: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_PS_OFFLINE_SHADER_COMPILER
    path: ../NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_PS_OFFLINE_SHADER_COMPILER
    content.vb: Public Enum EValues_PS_OFFLINE_SHADER_COMPILER
- uid: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_OFF
  commentId: F:NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_OFF
  id: PS_OFFLINE_SHADER_COMPILER_OFF
  parent: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  langs:
  - csharp
  - vb
  name: PS_OFFLINE_SHADER_COMPILER_OFF
  nameWithType: EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_OFF
  fullName: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_OFF
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_OFFLINE_SHADER_COMPILER_OFF
    path: ../NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_OFFLINE_SHADER_COMPILER_OFF = 119030616
    return:
      type: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
- uid: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_ON
  commentId: F:NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_ON
  id: PS_OFFLINE_SHADER_COMPILER_ON
  parent: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  langs:
  - csharp
  - vb
  name: PS_OFFLINE_SHADER_COMPILER_ON
  nameWithType: EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_ON
  fullName: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_ON
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_OFFLINE_SHADER_COMPILER_ON
    path: ../NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_OFFLINE_SHADER_COMPILER_ON = 1680965906
    return:
      type: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
- uid: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  id: PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  parent: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  langs:
  - csharp
  - vb
  name: PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  nameWithType: EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  fullName: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_OFFLINE_SHADER_COMPILER_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_OFFLINE_SHADER_COMPILER_NUM_VALUES = 2
    return:
      type: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
- uid: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_DEFAULT
  commentId: F:NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_DEFAULT
  id: PS_OFFLINE_SHADER_COMPILER_DEFAULT
  parent: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  langs:
  - csharp
  - vb
  name: PS_OFFLINE_SHADER_COMPILER_DEFAULT
  nameWithType: EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_DEFAULT
  fullName: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.PS_OFFLINE_SHADER_COMPILER_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_OFFLINE_SHADER_COMPILER_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_PS_OFFLINE_SHADER_COMPILER.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_OFFLINE_SHADER_COMPILER_DEFAULT = 119030616
    return:
      type: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  commentId: T:NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER.html
  name: EValues_PS_OFFLINE_SHADER_COMPILER
  nameWithType: EValues_PS_OFFLINE_SHADER_COMPILER
  fullName: NVAPIWrapper.EValues_PS_OFFLINE_SHADER_COMPILER
