### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  commentId: T:NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  id: EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  - NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  - NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  - NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  langs:
  - csharp
  - vb
  name: EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  nameWithType: EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  fullName: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_NGX_DLSSG_MULTI_FRAME_COUNT
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_NGX_DLSSG_MULTI_FRAME_COUNT
    content.vb: Public Enum EValues_NGX_DLSSG_MULTI_FRAME_COUNT
- uid: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  commentId: F:NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  id: NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  parent: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  langs:
  - csharp
  - vb
  name: NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  nameWithType: EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  fullName: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MIN
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSSG_MULTI_FRAME_COUNT_MIN
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSSG_MULTI_FRAME_COUNT_MIN = 1
    return:
      type: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
- uid: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  commentId: F:NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  id: NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  parent: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  langs:
  - csharp
  - vb
  name: NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  nameWithType: EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  fullName: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_MAX
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSSG_MULTI_FRAME_COUNT_MAX
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSSG_MULTI_FRAME_COUNT_MAX = 15
    return:
      type: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
- uid: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  commentId: F:NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  id: NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  parent: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  langs:
  - csharp
  - vb
  name: NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  nameWithType: EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  fullName: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT = 1
    return:
      type: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
- uid: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  id: NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  parent: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  langs:
  - csharp
  - vb
  name: NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  nameWithType: EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  fullName: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSSG_MULTI_FRAME_COUNT.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES = 3
    return:
      type: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  commentId: T:NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT.html
  name: EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  nameWithType: EValues_NGX_DLSSG_MULTI_FRAME_COUNT
  fullName: NVAPIWrapper.EValues_NGX_DLSSG_MULTI_FRAME_COUNT
