### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  commentId: T:NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  id: EValues_PS_TEXFILTER_ANISO_OPTS2
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  - NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  - NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_OFF
  - NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_ON
  langs:
  - csharp
  - vb
  name: EValues_PS_TEXFILTER_ANISO_OPTS2
  nameWithType: EValues_PS_TEXFILTER_ANISO_OPTS2
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_PS_TEXFILTER_ANISO_OPTS2
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_PS_TEXFILTER_ANISO_OPTS2
    content.vb: Public Enum EValues_PS_TEXFILTER_ANISO_OPTS2
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_OFF
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_OFF
  id: PS_TEXFILTER_ANISO_OPTS2_OFF
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_ANISO_OPTS2_OFF
  nameWithType: EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_OFF
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_OFF
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_ANISO_OPTS2_OFF
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_ANISO_OPTS2_OFF = 0
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_ON
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_ON
  id: PS_TEXFILTER_ANISO_OPTS2_ON
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_ANISO_OPTS2_ON
  nameWithType: EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_ON
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_ON
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_ANISO_OPTS2_ON
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_ANISO_OPTS2_ON = 1
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  id: PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  nameWithType: EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_ANISO_OPTS2_NUM_VALUES = 2
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  id: PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  nameWithType: EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.PS_TEXFILTER_ANISO_OPTS2_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_ANISO_OPTS2_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_ANISO_OPTS2.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_ANISO_OPTS2_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  commentId: T:NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2.html
  name: EValues_PS_TEXFILTER_ANISO_OPTS2
  nameWithType: EValues_PS_TEXFILTER_ANISO_OPTS2
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_ANISO_OPTS2
