### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  commentId: T:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  id: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1._bitfield
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.colorFormat
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.position
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.resolution
  - NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.spanningOrientation
  langs:
  - csharp
  - vb
  name: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  type: Struct
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public struct _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
    content.vb: Public Structure _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.resolution
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.resolution
  id: resolution
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: resolution
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.resolution
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.resolution
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: resolution
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 7
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public _NV_RESOLUTION resolution
    return:
      type: NVAPIWrapper._NV_RESOLUTION
    content.vb: Public resolution As _NV_RESOLUTION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.colorFormat
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.colorFormat
  id: colorFormat
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: colorFormat
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.colorFormat
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.colorFormat
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: colorFormat
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 11
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public _NV_FORMAT colorFormat
    return:
      type: NVAPIWrapper._NV_FORMAT
    content.vb: Public colorFormat As _NV_FORMAT
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.position
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.position
  id: position
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: position
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.position
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.position
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: position
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public _NV_POSITION position
    return:
      type: NVAPIWrapper._NV_POSITION
    content.vb: Public position As _NV_POSITION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.spanningOrientation
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.spanningOrientation
  id: spanningOrientation
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: spanningOrientation
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.spanningOrientation
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.spanningOrientation
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: spanningOrientation
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 19
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public _NV_DISPLAYCONFIG_SPANNING_ORIENTATION spanningOrientation
    return:
      type: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
    content.vb: Public spanningOrientation As _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1._bitfield
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1._bitfield
  id: _bitfield
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: _bitfield
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1._bitfield
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1._bitfield
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: _bitfield
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 21
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  syntax:
    content: public uint _bitfield
    return:
      type: System.UInt32
    content.vb: Public _bitfield As UInteger
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  commentId: P:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  id: bGDIPrimary
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: bGDIPrimary
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  type: Property
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: bGDIPrimary
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 24
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint bGDIPrimary { readonly get; set; }
    parameters: []
    return:
      type: System.UInt32
    content.vb: Public Property bGDIPrimary As UInteger
  overload: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary*
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  commentId: P:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  id: bSLIFocus
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: bSLIFocus
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  type: Property
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: bSLIFocus
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 39
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint bSLIFocus { readonly get; set; }
    parameters: []
    return:
      type: System.UInt32
    content.vb: Public Property bSLIFocus As UInteger
  overload: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus*
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  commentId: P:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  id: reserved
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1
  langs:
  - csharp
  - vb
  name: reserved
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  type: Property
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: reserved
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.cs
    startLine: 54
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint reserved { readonly get; set; }
    parameters: []
    return:
      type: System.UInt32
    content.vb: Public Property reserved As UInteger
  overload: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved*
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NVAPIWrapper._NV_RESOLUTION
  commentId: T:NVAPIWrapper._NV_RESOLUTION
  parent: NVAPIWrapper
  href: NVAPIWrapper._NV_RESOLUTION.html
  name: _NV_RESOLUTION
  nameWithType: _NV_RESOLUTION
  fullName: NVAPIWrapper._NV_RESOLUTION
- uid: NVAPIWrapper._NV_FORMAT
  commentId: T:NVAPIWrapper._NV_FORMAT
  parent: NVAPIWrapper
  href: NVAPIWrapper._NV_FORMAT.html
  name: _NV_FORMAT
  nameWithType: _NV_FORMAT
  fullName: NVAPIWrapper._NV_FORMAT
- uid: NVAPIWrapper._NV_POSITION
  commentId: T:NVAPIWrapper._NV_POSITION
  parent: NVAPIWrapper
  href: NVAPIWrapper._NV_POSITION.html
  name: _NV_POSITION
  nameWithType: _NV_POSITION
  fullName: NVAPIWrapper._NV_POSITION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  commentId: T:NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  parent: NVAPIWrapper
  href: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.html
  name: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  nameWithType: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary*
  commentId: Overload:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  href: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.html#NVAPIWrapper__NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1_bGDIPrimary
  name: bGDIPrimary
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bGDIPrimary
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus*
  commentId: Overload:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  href: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.html#NVAPIWrapper__NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1_bSLIFocus
  name: bSLIFocus
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.bSLIFocus
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved*
  commentId: Overload:NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  href: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.html#NVAPIWrapper__NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1_reserved
  name: reserved
  nameWithType: _NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SOURCE_MODE_INFO_V1.reserved
