### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  commentId: T:NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  id: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  - NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  - NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  - NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  langs:
  - csharp
  - vb
  name: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  nameWithType: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  fullName: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
    path: ../NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: 'public enum EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL : uint'
    content.vb: Public Enum EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL As UInteger
- uid: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  commentId: F:NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  parent: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  langs:
  - csharp
  - vb
  name: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  nameWithType: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  fullName: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES
    path: ../NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
    startLine: 7
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES = 0
    return:
      type: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
- uid: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  commentId: F:NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  parent: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  langs:
  - csharp
  - vb
  name: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  nameWithType: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  fullName: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES
    path: ../NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
    startLine: 10
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES = 100
    return:
      type: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
- uid: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  parent: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  langs:
  - csharp
  - vb
  name: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  nameWithType: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  fullName: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
    startLine: 13
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES = 2
    return:
      type: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
- uid: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  commentId: F:NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  parent: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  langs:
  - csharp
  - vb
  name: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  nameWithType: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  fullName: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.cs
    startLine: 16
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  commentId: T:NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL.html
  name: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  nameWithType: EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
  fullName: NVAPIWrapper.EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL
