### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  commentId: T:NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  id: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  - NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  - NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  - NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  langs:
  - csharp
  - vb
  name: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  nameWithType: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  fullName: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
    content.vb: Public Enum EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
- uid: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  parent: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  langs:
  - csharp
  - vb
  name: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  nameWithType: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  fullName: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE = 0
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
- uid: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  parent: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  langs:
  - csharp
  - vb
  name: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  nameWithType: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  fullName: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X = 1
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
- uid: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  parent: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  langs:
  - csharp
  - vb
  name: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  nameWithType: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  fullName: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES = 2
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
- uid: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  commentId: F:NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  parent: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  langs:
  - csharp
  - vb
  name: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  nameWithType: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  fullName: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  commentId: T:NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS.html
  name: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  nameWithType: EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
  fullName: NVAPIWrapper.EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS
