### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  commentId: T:NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  id: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.controller
  - NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.currentTemp
  - NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMaxTemp
  - NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMinTemp
  - NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.target
  langs:
  - csharp
  - vb
  name: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  nameWithType: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  fullName: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  type: Struct
  source:
    remote:
      path: NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: _sensor_e__Struct
    path: ../NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
    startLine: 20
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public struct NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
    content.vb: Public Structure NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.controller
  commentId: F:NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.controller
  id: controller
  parent: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  langs:
  - csharp
  - vb
  name: controller
  nameWithType: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.controller
  fullName: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.controller
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: controller
    path: ../NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
    startLine: 23
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public NV_THERMAL_CONTROLLER controller
    return:
      type: NVAPIWrapper.NV_THERMAL_CONTROLLER
    content.vb: Public controller As NV_THERMAL_CONTROLLER
- uid: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMinTemp
  commentId: F:NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMinTemp
  id: defaultMinTemp
  parent: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  langs:
  - csharp
  - vb
  name: defaultMinTemp
  nameWithType: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMinTemp
  fullName: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMinTemp
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: defaultMinTemp
    path: ../NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
    startLine: 27
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint defaultMinTemp
    return:
      type: System.UInt32
    content.vb: Public defaultMinTemp As UInteger
- uid: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMaxTemp
  commentId: F:NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMaxTemp
  id: defaultMaxTemp
  parent: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  langs:
  - csharp
  - vb
  name: defaultMaxTemp
  nameWithType: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMaxTemp
  fullName: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.defaultMaxTemp
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: defaultMaxTemp
    path: ../NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
    startLine: 31
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint defaultMaxTemp
    return:
      type: System.UInt32
    content.vb: Public defaultMaxTemp As UInteger
- uid: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.currentTemp
  commentId: F:NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.currentTemp
  id: currentTemp
  parent: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  langs:
  - csharp
  - vb
  name: currentTemp
  nameWithType: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.currentTemp
  fullName: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.currentTemp
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: currentTemp
    path: ../NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
    startLine: 35
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint currentTemp
    return:
      type: System.UInt32
    content.vb: Public currentTemp As UInteger
- uid: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.target
  commentId: F:NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.target
  id: target
  parent: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct
  langs:
  - csharp
  - vb
  name: target
  nameWithType: NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.target
  fullName: NVAPIWrapper.NV_GPU_THERMAL_SETTINGS_V1._sensor_e__Struct.target
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: target
    path: ../NVAPIWrapper/cs_generated/NV_GPU_THERMAL_SETTINGS_V1.cs
    startLine: 38
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public NV_THERMAL_TARGET target
    return:
      type: NVAPIWrapper.NV_THERMAL_TARGET
    content.vb: Public target As NV_THERMAL_TARGET
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NVAPIWrapper.NV_THERMAL_CONTROLLER
  commentId: T:NVAPIWrapper.NV_THERMAL_CONTROLLER
  parent: NVAPIWrapper
  href: NVAPIWrapper.NV_THERMAL_CONTROLLER.html
  name: NV_THERMAL_CONTROLLER
  nameWithType: NV_THERMAL_CONTROLLER
  fullName: NVAPIWrapper.NV_THERMAL_CONTROLLER
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: NVAPIWrapper.NV_THERMAL_TARGET
  commentId: T:NVAPIWrapper.NV_THERMAL_TARGET
  parent: NVAPIWrapper
  href: NVAPIWrapper.NV_THERMAL_TARGET.html
  name: NV_THERMAL_TARGET
  nameWithType: NV_THERMAL_TARGET
  fullName: NVAPIWrapper.NV_THERMAL_TARGET
