### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  commentId: T:NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  id: EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  - NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  - NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  - NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_ON
  langs:
  - csharp
  - vb
  name: EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  nameWithType: EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_PS_TEXFILTER_NO_NEG_LODBIAS
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_PS_TEXFILTER_NO_NEG_LODBIAS
    content.vb: Public Enum EValues_PS_TEXFILTER_NO_NEG_LODBIAS
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  id: PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  nameWithType: EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_OFF
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_NO_NEG_LODBIAS_OFF
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_NO_NEG_LODBIAS_OFF = 0
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_ON
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_ON
  id: PS_TEXFILTER_NO_NEG_LODBIAS_ON
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_NO_NEG_LODBIAS_ON
  nameWithType: EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_ON
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_ON
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_NO_NEG_LODBIAS_ON
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_NO_NEG_LODBIAS_ON = 1
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  id: PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  nameWithType: EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES = 2
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  commentId: F:NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  id: PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  parent: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  langs:
  - csharp
  - vb
  name: PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  nameWithType: EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_PS_TEXFILTER_NO_NEG_LODBIAS.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  commentId: T:NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS.html
  name: EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  nameWithType: EValues_PS_TEXFILTER_NO_NEG_LODBIAS
  fullName: NVAPIWrapper.EValues_PS_TEXFILTER_NO_NEG_LODBIAS
