### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  commentId: T:NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  id: _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.reserved_sourceId
  - NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.sourceId
  langs:
  - csharp
  - vb
  name: _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  nameWithType: _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  type: Struct
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_PATH_INFO.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: _Anonymous_e__Union
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_PATH_INFO.cs
    startLine: 84
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public struct _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
    content.vb: Public Structure _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.sourceId
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.sourceId
  id: sourceId
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  langs:
  - csharp
  - vb
  name: sourceId
  nameWithType: _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.sourceId
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.sourceId
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_PATH_INFO.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: sourceId
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_PATH_INFO.cs
    startLine: 90
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint sourceId
    return:
      type: System.UInt32
    content.vb: Public sourceId As UInteger
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.reserved_sourceId
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.reserved_sourceId
  id: reserved_sourceId
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union
  langs:
  - csharp
  - vb
  name: reserved_sourceId
  nameWithType: _NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.reserved_sourceId
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_PATH_INFO._Anonymous_e__Union.reserved_sourceId
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_PATH_INFO.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: reserved_sourceId
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_PATH_INFO.cs
    startLine: 95
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint reserved_sourceId
    return:
      type: System.UInt32
    content.vb: Public reserved_sourceId As UInteger
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
