### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  commentId: T:NVAPIWrapper.EValues_AA_MODE_SELECTOR
  id: EValues_AA_MODE_SELECTOR
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_APP_CONTROL
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_DEFAULT
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_ENHANCE
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MASK
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MAX
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_NUM_VALUES
  - NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_OVERRIDE
  langs:
  - csharp
  - vb
  name: EValues_AA_MODE_SELECTOR
  nameWithType: EValues_AA_MODE_SELECTOR
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_AA_MODE_SELECTOR
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_AA_MODE_SELECTOR
    content.vb: Public Enum EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MASK
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MASK
  id: AA_MODE_SELECTOR_MASK
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_MASK
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MASK
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MASK
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_MASK
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_MASK = 3
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_APP_CONTROL
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_APP_CONTROL
  id: AA_MODE_SELECTOR_APP_CONTROL
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_APP_CONTROL
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_APP_CONTROL
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_APP_CONTROL
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_APP_CONTROL
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_APP_CONTROL = 0
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_OVERRIDE
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_OVERRIDE
  id: AA_MODE_SELECTOR_OVERRIDE
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_OVERRIDE
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_OVERRIDE
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_OVERRIDE
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_OVERRIDE
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_OVERRIDE = 1
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_ENHANCE
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_ENHANCE
  id: AA_MODE_SELECTOR_ENHANCE
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_ENHANCE
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_ENHANCE
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_ENHANCE
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_ENHANCE
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_ENHANCE = 2
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MAX
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MAX
  id: AA_MODE_SELECTOR_MAX
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_MAX
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MAX
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_MAX
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_MAX
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 18
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_MAX = 2
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_NUM_VALUES
  id: AA_MODE_SELECTOR_NUM_VALUES
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_NUM_VALUES
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_NUM_VALUES
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 21
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_NUM_VALUES = 5
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_DEFAULT
  commentId: F:NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_DEFAULT
  id: AA_MODE_SELECTOR_DEFAULT
  parent: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  langs:
  - csharp
  - vb
  name: AA_MODE_SELECTOR_DEFAULT
  nameWithType: EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_DEFAULT
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR.AA_MODE_SELECTOR_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: AA_MODE_SELECTOR_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_AA_MODE_SELECTOR.cs
    startLine: 24
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: AA_MODE_SELECTOR_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_AA_MODE_SELECTOR
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_AA_MODE_SELECTOR
  commentId: T:NVAPIWrapper.EValues_AA_MODE_SELECTOR
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_AA_MODE_SELECTOR.html
  name: EValues_AA_MODE_SELECTOR
  nameWithType: EValues_AA_MODE_SELECTOR
  fullName: NVAPIWrapper.EValues_AA_MODE_SELECTOR
