### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  commentId: T:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  id: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  - NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  langs:
  - csharp
  - vb
  name: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
    content.vb: Public Enum EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED = 0
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS = 9
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS = 15
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS = 30
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 18
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE = 60
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 21
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES = 120
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 24
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES = 6
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  commentId: F:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  parent: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  langs:
  - csharp
  - vb
  name: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.cs
    startLine: 27
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  commentId: T:NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT.html
  name: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  nameWithType: EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
  fullName: NVAPIWrapper.EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT
