### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  commentId: T:NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  id: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  - NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  - NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  - NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  langs:
  - csharp
  - vb
  name: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  nameWithType: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  fullName: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
    path: ../NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
    content.vb: Public Enum EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
- uid: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  commentId: F:NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  id: QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  parent: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  langs:
  - csharp
  - vb
  name: QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  nameWithType: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  fullName: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION
    path: ../NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION = 0
    return:
      type: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
- uid: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  commentId: F:NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  id: QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  parent: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  langs:
  - csharp
  - vb
  name: QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  nameWithType: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  fullName: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY
    path: ../NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY = 1
    return:
      type: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
- uid: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  id: QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  parent: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  langs:
  - csharp
  - vb
  name: QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  nameWithType: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  fullName: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES = 2
    return:
      type: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
- uid: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  commentId: F:NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  id: QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  parent: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  langs:
  - csharp
  - vb
  name: QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  nameWithType: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  fullName: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  commentId: T:NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION.html
  name: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  nameWithType: EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
  fullName: NVAPIWrapper.EValues_QUALITY_ENHANCEMENT_SUBSTITUTION
