### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
  commentId: T:NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
  id: _NVDRS_SETTING_VALUES._Anonymous_e__Union
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.binaryDefaultValue
  - NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.u32DefaultValue
  - NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.wszDefaultValue
  langs:
  - csharp
  - vb
  name: _NVDRS_SETTING_VALUES._Anonymous_e__Union
  nameWithType: _NVDRS_SETTING_VALUES._Anonymous_e__Union
  fullName: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
  type: Struct
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: _Anonymous_e__Union
    path: ../NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
    startLine: 61
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public struct _NVDRS_SETTING_VALUES._Anonymous_e__Union
    content.vb: Public Structure _NVDRS_SETTING_VALUES._Anonymous_e__Union
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.u32DefaultValue
  commentId: F:NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.u32DefaultValue
  id: u32DefaultValue
  parent: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
  langs:
  - csharp
  - vb
  name: u32DefaultValue
  nameWithType: _NVDRS_SETTING_VALUES._Anonymous_e__Union.u32DefaultValue
  fullName: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.u32DefaultValue
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: u32DefaultValue
    path: ../NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
    startLine: 67
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public uint u32DefaultValue
    return:
      type: System.UInt32
    content.vb: Public u32DefaultValue As UInteger
- uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.binaryDefaultValue
  commentId: F:NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.binaryDefaultValue
  id: binaryDefaultValue
  parent: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
  langs:
  - csharp
  - vb
  name: binaryDefaultValue
  nameWithType: _NVDRS_SETTING_VALUES._Anonymous_e__Union.binaryDefaultValue
  fullName: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.binaryDefaultValue
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: binaryDefaultValue
    path: ../NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
    startLine: 72
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public _NVDRS_BINARY_SETTING binaryDefaultValue
    return:
      type: NVAPIWrapper._NVDRS_BINARY_SETTING
    content.vb: Public binaryDefaultValue As _NVDRS_BINARY_SETTING
- uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.wszDefaultValue
  commentId: F:NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.wszDefaultValue
  id: wszDefaultValue
  parent: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
  langs:
  - csharp
  - vb
  name: wszDefaultValue
  nameWithType: _NVDRS_SETTING_VALUES._Anonymous_e__Union.wszDefaultValue
  fullName: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.wszDefaultValue
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: wszDefaultValue
    path: ../NVAPIWrapper/cs_generated/_NVDRS_SETTING_VALUES.cs
    startLine: 77
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public _NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer wszDefaultValue
    return:
      type: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
    content.vb: Public wszDefaultValue As _NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: NVAPIWrapper._NVDRS_BINARY_SETTING
  commentId: T:NVAPIWrapper._NVDRS_BINARY_SETTING
  parent: NVAPIWrapper
  href: NVAPIWrapper._NVDRS_BINARY_SETTING.html
  name: _NVDRS_BINARY_SETTING
  nameWithType: _NVDRS_BINARY_SETTING
  fullName: NVAPIWrapper._NVDRS_BINARY_SETTING
- uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
  commentId: T:NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
  parent: NVAPIWrapper
  href: NVAPIWrapper._NVDRS_SETTING_VALUES.html
  name: _NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
  nameWithType: _NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
  fullName: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
  spec.csharp:
  - uid: NVAPIWrapper._NVDRS_SETTING_VALUES
    name: _NVDRS_SETTING_VALUES
    href: NVAPIWrapper._NVDRS_SETTING_VALUES.html
  - name: .
  - uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
    name: _Anonymous_e__Union
    href: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.html
  - name: .
  - uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
    name: _wszDefaultValue_e__FixedBuffer
    href: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer.html
  spec.vb:
  - uid: NVAPIWrapper._NVDRS_SETTING_VALUES
    name: _NVDRS_SETTING_VALUES
    href: NVAPIWrapper._NVDRS_SETTING_VALUES.html
  - name: .
  - uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union
    name: _Anonymous_e__Union
    href: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union.html
  - name: .
  - uid: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer
    name: _wszDefaultValue_e__FixedBuffer
    href: NVAPIWrapper._NVDRS_SETTING_VALUES._Anonymous_e__Union._wszDefaultValue_e__FixedBuffer.html
