### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  commentId: T:NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  id: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  - NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_NONE
  - NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_VERTICAL
  langs:
  - csharp
  - vb
  name: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  nameWithType: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
    content.vb: Public Enum _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_NONE
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_NONE
  id: NV_DISPLAYCONFIG_SPAN_NONE
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  langs:
  - csharp
  - vb
  name: NV_DISPLAYCONFIG_SPAN_NONE
  nameWithType: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_NONE
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_NONE
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NV_DISPLAYCONFIG_SPAN_NONE
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NV_DISPLAYCONFIG_SPAN_NONE = 0
    return:
      type: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  id: NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  langs:
  - csharp
  - vb
  name: NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  nameWithType: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_HORIZONTAL
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NV_DISPLAYCONFIG_SPAN_HORIZONTAL
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NV_DISPLAYCONFIG_SPAN_HORIZONTAL = 1
    return:
      type: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_VERTICAL
  commentId: F:NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_VERTICAL
  id: NV_DISPLAYCONFIG_SPAN_VERTICAL
  parent: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  langs:
  - csharp
  - vb
  name: NV_DISPLAYCONFIG_SPAN_VERTICAL
  nameWithType: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_VERTICAL
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.NV_DISPLAYCONFIG_SPAN_VERTICAL
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: NV_DISPLAYCONFIG_SPAN_VERTICAL
    path: ../NVAPIWrapper/cs_generated/_NV_DISPLAYCONFIG_SPANNING_ORIENTATION.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: NV_DISPLAYCONFIG_SPAN_VERTICAL = 2
    return:
      type: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  commentId: T:NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  parent: NVAPIWrapper
  href: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION.html
  name: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  nameWithType: _NV_DISPLAYCONFIG_SPANNING_ORIENTATION
  fullName: NVAPIWrapper._NV_DISPLAYCONFIG_SPANNING_ORIENTATION
