### YamlMime:ManagedReference
items:
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  commentId: T:NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  id: EValues_VRR_APP_OVERRIDE
  parent: NVAPIWrapper
  children:
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ALLOW
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DEFAULT
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DISALLOW
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FIXED_REFRESH
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FORCE_OFF
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_NUM_VALUES
  - NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ULMB
  langs:
  - csharp
  - vb
  name: EValues_VRR_APP_OVERRIDE
  nameWithType: EValues_VRR_APP_OVERRIDE
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  type: Enum
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: EValues_VRR_APP_OVERRIDE
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 3
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: public enum EValues_VRR_APP_OVERRIDE
    content.vb: Public Enum EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ALLOW
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ALLOW
  id: VRR_APP_OVERRIDE_ALLOW
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_ALLOW
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ALLOW
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ALLOW
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_ALLOW
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 6
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_ALLOW = 0
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FORCE_OFF
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FORCE_OFF
  id: VRR_APP_OVERRIDE_FORCE_OFF
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_FORCE_OFF
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FORCE_OFF
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FORCE_OFF
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_FORCE_OFF
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 9
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_FORCE_OFF = 1
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DISALLOW
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DISALLOW
  id: VRR_APP_OVERRIDE_DISALLOW
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_DISALLOW
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DISALLOW
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DISALLOW
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_DISALLOW
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 12
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_DISALLOW = 2
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ULMB
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ULMB
  id: VRR_APP_OVERRIDE_ULMB
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_ULMB
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ULMB
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_ULMB
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_ULMB
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 15
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_ULMB = 3
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FIXED_REFRESH
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FIXED_REFRESH
  id: VRR_APP_OVERRIDE_FIXED_REFRESH
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_FIXED_REFRESH
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FIXED_REFRESH
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_FIXED_REFRESH
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_FIXED_REFRESH
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 18
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_FIXED_REFRESH = 4
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_NUM_VALUES
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_NUM_VALUES
  id: VRR_APP_OVERRIDE_NUM_VALUES
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_NUM_VALUES
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_NUM_VALUES
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_NUM_VALUES
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_NUM_VALUES
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 21
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_NUM_VALUES = 5
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DEFAULT
  commentId: F:NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DEFAULT
  id: VRR_APP_OVERRIDE_DEFAULT
  parent: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  langs:
  - csharp
  - vb
  name: VRR_APP_OVERRIDE_DEFAULT
  nameWithType: EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DEFAULT
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.VRR_APP_OVERRIDE_DEFAULT
  type: Field
  source:
    remote:
      path: NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
      branch: main
      repo: https://github.com/terrymacdonald/NVAPIWrapper.git
    id: VRR_APP_OVERRIDE_DEFAULT
    path: ../NVAPIWrapper/cs_generated/EValues_VRR_APP_OVERRIDE.cs
    startLine: 24
  assemblies:
  - NVAPIWrapper
  namespace: NVAPIWrapper
  example: []
  syntax:
    content: VRR_APP_OVERRIDE_DEFAULT = 0
    return:
      type: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
references:
- uid: NVAPIWrapper
  commentId: N:NVAPIWrapper
  href: NVAPIWrapper.html
  name: NVAPIWrapper
  nameWithType: NVAPIWrapper
  fullName: NVAPIWrapper
- uid: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  commentId: T:NVAPIWrapper.EValues_VRR_APP_OVERRIDE
  parent: NVAPIWrapper
  href: NVAPIWrapper.EValues_VRR_APP_OVERRIDE.html
  name: EValues_VRR_APP_OVERRIDE
  nameWithType: EValues_VRR_APP_OVERRIDE
  fullName: NVAPIWrapper.EValues_VRR_APP_OVERRIDE
